# Generated by Django 6.0.2 on 2026-03-06 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_matched', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('name_normalized', models.CharField(db_index=True, max_length=255)),
                ('building', models.CharField(blank=True, max_length=64, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('borough', models.CharField(blank=True, max_length=80, null=True)),
                ('zip_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('cuisine_tags', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('composite_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade_latest', models.CharField(blank=True, max_length=16, null=True)),
                ('grade_score_latest', models.IntegerField(blank=True, null=True)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('composite_score_calculated_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name_normalized', 'zip_code'], name='nomz_restau_name_no_1bc4bb_idx'), models.Index(fields=['borough', 'zip_code'], name='nomz_restau_borough_8e6a1a_idx'), models.Index(fields=['is_active'], name='nomz_restau_is_acti_f59dd9_idx'), models.Index(fields=['latitude', 'longitude'], name='nomz_restau_latitud_09565a_idx')],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspection_key', models.CharField(max_length=200)),
                ('grade', models.CharField(blank=True, max_length=12, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('critical_violations', models.IntegerField(default=0)),
                ('noncritical_violations', models.IntegerField(default=0)),
                ('violation_count', models.IntegerField(default=0)),
                ('inspection_type', models.CharField(blank=True, max_length=128, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('violations', models.JSONField(blank=True, default=list)),
                ('camis', models.CharField(blank=True, max_length=80, null=True)),
                ('boro', models.CharField(blank=True, max_length=80, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='nomz.restaurant')),
            ],
            options={
                'ordering': ['-inspection_date'],
                'indexes': [models.Index(fields=['restaurant', 'inspection_date'], name='nomz_inspec_restaur_035d0b_idx'), models.Index(fields=['grade'], name='nomz_inspec_grade_c214b2_idx')],
                'unique_together': {('restaurant', 'inspection_key')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantSourceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('EATERIES', 'Directory of Eateries'), ('DINING_OUT', 'Dining Out NYC Locations'), ('DOHMH', 'DOHMH Inspection Results')], max_length=20)),
                ('external_id', models.CharField(max_length=200)),
                ('external_name', models.CharField(max_length=255)),
                ('external_address', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='nomz.restaurant')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'external_id'], name='nomz_restau_source_160b12_idx'), models.Index(fields=['restaurant', 'source'], name='nomz_restau_restaur_446d59_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
