# Generated by Django 4.2.19 on 2026-03-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0008_userpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginlog",
            name="is_user_suspicious",
            field=models.BooleanField(default=False),
        ),
    ]
