# Generated by Django 6.0.2 on 2026-04-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nomz", "0031_alter_userprofile_is_approved"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RestaurantPhoto",
        ),
    ]
